import React, { useState } from "react";
import Loading from '../components/interactives/loading';

export default function Forum() {
    const [selectedInputType, setSelectedInputType] = useState<string | null>(null);
    const [isProcessing, setIsProcessing] = useState(false);

    const features = [
        {
            title: "Web Content Analysis",
            description: "Detect similarities with online content and identify potential copy-paste from web sources",
            icon: "🌐",
            highlight: "90% accuracy in detecting web-sourced content"
        },
        {
            title: "Cross-Submission Check",
            description: "Compare submissions against each other to identify potential collaboration or sharing",
            icon: "🔄",
            highlight: "Compare up to 1000 submissions simultaneously"
        },
        {
            title: "AI Content Detection",
            description: "Identify content potentially generated by AI tools like ChatGPT",
            icon: "🤖",
            highlight: "Latest AI detection algorithms"
        }
    ];

    const inputTypes = [
        {
            id: 'api',
            title: 'Using API',
            description: 'Connect directly to source using API',
            icon: '🔌'
        },
        {
            id: 'manual',
            title: 'Manual Input',
            description: 'Input URLs or links one by one',
            icon: '🔗'
        },
        {
            id: 'excel',
            title: 'Excel Upload',
            description: 'Upload Excel file containing multiple links',
            icon: '📊'
        }
    ];

    const renderInputForm = () => {
        switch (selectedInputType) {
            case 'api':
                return (
                    <div className="mt-8 bg-white text-white dark:bg-gray-800 p-6 rounded-xl">
                        <h3 className="text-xl font-bold mb-4">API Configuration</h3>
                        <input
                            type="text"
                            placeholder="API Endpoint"
                            className="w-full mb-4 p-2 border rounded dark:bg-gray-700 dark:border-gray-600"
                        />
                        <input
                            type="text"
                            placeholder="API Key"
                            className="w-full mb-4 p-2 border rounded dark:bg-gray-700 dark:border-gray-600"
                        />
                    </div>
                );
            case 'manual':
                return (
                    <div className="mt-8 bg-white text-white dark:bg-gray-800 p-6 rounded-xl">
                        <h3 className="text-xl font-bold mb-4">Enter URLs</h3>
                        <textarea
                            placeholder="Enter URLs (one per line)"
                            className="w-full h-32 mb-4 p-2 border rounded dark:bg-gray-700 dark:border-gray-600"
                        />
                    </div>
                );
            case 'excel':
                return (
                    <div className="mt-8 bg-white text-white dark:bg-gray-800 p-6 rounded-xl">
                        <h3 className="text-xl font-bold mb-4">Upload Excel File</h3>
                        <div className="border-2 border-dashed border-gray-300 dark:border-gray-600 p-8 text-center rounded-lg">
                            <input
                                type="file"
                                accept=".xlsx,.xls"
                                className="hidden"
                                id="excel-upload"
                            />
                            <label
                                htmlFor="excel-upload"
                                className="cursor-pointer text-blue-500 hover:text-blue-600"
                            >
                                <span className="text-4xl mb-2 block">📁</span>
                                <span>Click to upload Excel file</span>
                            </label>
                        </div>
                    </div>
                );
            default:
                return null;
        }
    };

    const handleProcess = async () => {
        setIsProcessing(true);
        await new Promise(resolve => setTimeout(resolve, 2000));
        setIsProcessing(false);
    };

    return (
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
            <div className="mb-16">
                <h1 className="text-4xl font-bold text-gray-800 dark:text-white text-center mb-12">
                    Features Quick Explanation 
                </h1>
                <div className="space-y-12">
                    {features.map((feature, index) => (
                        <div 
                            key={index}
                            className={`flex items-center gap-8 ${
                                'flex-row'
                            }`}
                        >
                            <div className={`w-1/2 ${
                                'pl-8 border-l'
                            } border-blue-500`}>
                                <div className="flex items-center gap-4 mb-4">
                                    <span className="text-4xl">{feature.icon}</span>
                                    <h3 className="text-2xl font-bold text-gray-800 dark:text-white">
                                        {feature.title}
                                    </h3>
                                </div>
                                <p className="text-gray-600 dark:text-gray-300 mb-4">
                                    {feature.description}
                                </p>
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-8 text-center">
                Select Input Method
            </h2>

            <div className="grid md:grid-cols-3 gap-6">
                {inputTypes.map((type) => (
                    <div
                        key={type.id}
                        className={`
                            p-6 rounded-xl cursor-pointer transition-all duration-200
                            ${selectedInputType === type.id
                                ? 'bg-blue-500 text-white shadow-xl transform -translate-y-1'
                                : 'bg-white dark:bg-gray-800 text-gray-800 dark:text-white hover:shadow-lg'
                            }
                        `}
                        onClick={() => setSelectedInputType(type.id)}
                    >
                        <div className="text-4xl mb-4">{type.icon}</div>
                        <h3 className="text-xl font-bold mb-2">{type.title}</h3>
                        <p className={`
                            ${selectedInputType === type.id
                                ? 'text-gray-100'
                                : 'text-gray-600 dark:text-gray-300'
                            }
                        `}>
                            {type.description}
                        </p>
                    </div>
                ))}
            </div>
            {renderInputForm()}
            {selectedInputType && (
                <div className="mt-8 text-center">
                    {isProcessing ? (
                        <div className="flex flex-col items-center space-y-4">
                            <Loading size="large" />
                            <p className="text-gray-600 dark:text-gray-300">
                                Processing your request...
                            </p>
                        </div>
                    ) : (
                        <button
                            className="bg-blue-500 text-white px-8 py-3 rounded-lg hover:bg-blue-600 transition-colors"
                            onClick={handleProcess}
                        >
                            Process
                        </button>
                    )}
                </div>
            )}
        </div>
    );
}